In [ ]:
# 주성분분석 : 주성분을 찾는 메카니즘. 인공신경망에 층/노드를 구성하는 메커니즘

In [2]:
import pandas as pd
from sklearn.decomposition import PCA

In [ ]:
# 1. 데이터프레임 생성
df = pd.DataFrame({
    '키': [160, 165, 172, 168, 180],
    '몸무게': [55, 63, 60, 75, 68],
    '나이': [20, 35, 25, 45, 30]
})

display(df)

# 2. PCA: 변수 3개를 2개로 축소
pca = PCA(n_components=2) # 2개의 주성분으로 줄이는 객체
X_pca = pca.fit_transform(df)

# 3. 결과 확인
df_pca = pd.DataFrame(X_pca, columns=['주성분1', '주성분2'])
display(df_pca)

# 4. 각 주성분의 설명력
display(pca.explained_variance_ratio_)

     키  몸무게  나이
0  160   55  20
1  165   63  35
2  172   60  25
3  168   75  45
4  180   68  30

        주성분1       주성분2
0 -16.146057  -4.909677
1   1.241246  -5.265560
2  -6.308937   4.708793
3  16.849193  -5.357561
4   4.364555  10.824005

array([0.72644472, 0.26400856])