In [3]:
# 1. 데이터 블러오기 및 탐색
# pandas.read_csv() 함수
# DataFrame.Shape, DataFrame.head(), DataFrame.tail, DataFrame.info() 
# DataFrame.describe(), DataFrame.isnull(), DataFrame.isna()

import pandas as pd

train = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/8_2_train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/8_2_test.csv')

In [9]:
print(train.shape)
print(test.shape)
display(train.head())
display(test.head())
display(train['count'].describe())

(378, 9)
(166, 9)

,ID,holiday,workingday,weather,temp,atemp,humidity,windspeed,count
0,1017,No,No,Light Rain,11.48,12.120,100,27.9993,11
1,8921,No,Yes,Clear,27.88,31.820,79,16.9979,27
2,878,No,Yes,Clear,12.30,13.635,70,31.0009,7
3,7845,No,Yes,Clear,19.68,23.485,82,6.0032,34
4,6526,No,Yes,Clear,18.86,22.725,77,35.0008,7

      ID holiday workingday weather   temp   atemp  humidity  windspeed  count
0   4775      No         No   Clear   9.84  12.120        60     8.9981    NaN
1  10539      No        Yes   Clear  18.04  21.970        41    19.0012    NaN
2   8229     Yes         No   Clear  27.06  31.060        69     0.0000    NaN
3   8677      No        Yes    Mist  31.16  36.365        66    12.9980    NaN
4   5071      No        Yes   Clear  13.12  17.425        93     0.0000    NaN

count    378.000000
mean     189.169312
std      182.011361
min        1.000000
25%       44.250000
50%      144.500000
75%      273.500000
max      977.000000
Name: count, dtype: float64

In [11]:
train.info()
test.info()

print(train.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          378 non-null    int64
 1   holiday     378 non-null    str
 2   workingday  378 non-null    str
 3   weather     378 non-null    str
 4   temp        378 non-null    float64
 5   atemp       378 non-null    float64
 6   humidity    378 non-null    int64
 7   windspeed   378 non-null    float64
 8   count       378 non-null    int64
dtypes: float64(3), int64(3), str(3)
memory usage: 26.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          166 non-null    int64
 1   holiday     166 non-null    str
 2   workingday  166 non-null    str
 3   weather     166 non-null    str
 4   temp        166 non-null    float64
 5   atemp       166 non-null    float64
 6   humidity    166 non-null    int64
 7   windspeed   166 non-null    float64
 8   count       0 non-null      float64
dtypes: float64(4), int64(2), str(3)
memory usage: 11.8 KB
ID            0
holiday       0
workingday    0
weather       0
temp          0
atemp         0
humidity      0
windspeed     0
count         0
dtype: int64

In [13]:
# 2. X, y 분리
# 인덱싱 DataFrame[], DataFrame.loc[], DataFrame.iloc[]
# DataFrame.drop(axis=)
# 식별자 컬럼(ID) 분리, y(count) 분리 
X = train.drop(columns=['ID', 'count'])
display(X.head(3))

y = train['count']
display(y.head(3))

  holiday workingday     weather   temp   atemp  humidity  windspeed
0      No         No  Light Rain  11.48  12.120       100    27.9993
1      No        Yes       Clear  27.88  31.820        79    16.9979
2      No        Yes       Clear  12.30  13.635        70    31.0009

0    11
1    27
2     7
Name: count, dtype: int64

In [ ]:
X_test = test.drop(columns=['ID', 'count'])
test_id = test['ID']

display(X_test.head(3))
display(test_id.head(3))

  holiday workingday weather   temp  atemp  humidity  windspeed
0      No         No   Clear   9.84  12.12        60     8.9981
1      No        Yes   Clear  18.04  21.97        41    19.0012
2     Yes         No   Clear  27.06  31.06        69     0.0000

0     4775
1    10539
2     8229
Name: ID, dtype: int64

In [15]:
# 3. 데이터 분할(train, val, test)
# X, y를 분할
# 학습 : X_train, y_train
# 검증 : X_val, y_val

# 예측 : X_test
# sklearn.model_selection.train_test_split() 함수

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=1)

print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(264, 7)
(114, 7)
(264,)
(114,)

In [ ]:
# 4. 전처리(비지도 학습)
# 점주형 변수 -> 인코딩
# 연속형 숫자 변수 -> 스케일링(표준화/정규화) -> 모델()KNN, SVM)에 따라 선택
# DataFrame.select_dtypes('object/number).columns -> object/number 컬럼명 리스트
# DataFrame.value_counts()
cat_columns = X_train.select_dtypes('object').columns
num_columns = X_train.select_dtypes('number').columns
print('cat_columns :', cat_columns)
print('num_columns :', num_columns)

# 카테고리(범주형) 컬럼값 -> DataFrame.valu_counts() -> 탐색
# ['holiday', 'workingday', 'weather']
for col in cat_columns:
    print(col)
    display(X_train[col].value_counts())

cat_columns : Index(['holiday', 'workingday', 'weather'], dtype='str')
num_columns : Index(['temp', 'atemp', 'humidity', 'windspeed'], dtype='str')
holiday

C:\Users\user\AppData\Local\Temp\ipykernel_20736\1636733860.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_columns = X_train.select_dtypes('object').columns

holiday
No     256
Yes      8
Name: count, dtype: int64

workingday

workingday
Yes    174
No      90
Name: count, dtype: int64

weather

weather
Clear         168
Mist           75
Light Rain     21
Name: count, dtype: int64

In [19]:
# 전처리 -> 비지도 학습(인코딩, 스케일링, ...) -> 저장
# sklearn.preprocessing.OneHotEncoder, OneHotEncoder.set_output(transfrom='pandas)
# sklearn.preprocessing.StandardScaler, StandardScaler.set_output(transfrom='pandas)

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

# sparse_output : 기본값이 numpy배열이 아니다 / handle_unknown : 기본값 error
# encoder, scaler, model 따로 파일 형태로 저장필요
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore').set_output(transform='pandas') 
scaler = StandardScaler().set_output(transform='pandas')

In [25]:
# X_train, X_val, X_test의 cat_columns 변수값을 인코딩
# encoder가 필요한 변수 - cat_columns 변수에 저장
X_train_en = encoder.fit_transform(X_train[cat_columns])  # 3개의 컬럼 -> 7개의 컬럼으로 반환
X_val_en = encoder.transform(X_val[cat_columns])
X_test_en = encoder.transform(X_test[cat_columns])

display(X_train_en.head(3))
display(X_val_en.head(3))
display(X_test_en.head(3))

# DataFrame.concat([df1, df2], axis=1) 함수
X_train_pre = pd.concat([X_train_en, X_train[num_columns]], axis=1)
X_val_pre = pd.concat([X_val_en, X_val[num_columns]], axis=1)
X_test_pre = pd.concat([X_test_en, X_test[num_columns]], axis=1)

display(X_train_en.head(3))
display(X_val_en.head(3))
display(X_test_en.head(3))


# SVR모델 사용시 X_train, X_val, X_test의 num_columns 변수값을 인코딩
# scaler가 필요한 변수 - nun_columns 변수에 저장

# 데이터셋을 결합 ex) X_train의 숫자 + X_train_en

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist
346,1.0,0.0,0.0,1.0,1.0,0.0,0.0
338,1.0,0.0,0.0,1.0,1.0,0.0,0.0
238,1.0,0.0,0.0,1.0,1.0,0.0,0.0

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist
138,1.0,0.0,0.0,1.0,0.0,0.0,1.0
214,1.0,0.0,0.0,1.0,0.0,1.0,0.0
90,1.0,0.0,0.0,1.0,0.0,1.0,0.0

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist
0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist
346,1.0,0.0,0.0,1.0,1.0,0.0,0.0
338,1.0,0.0,0.0,1.0,1.0,0.0,0.0
238,1.0,0.0,0.0,1.0,1.0,0.0,0.0

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist
138,1.0,0.0,0.0,1.0,0.0,0.0,1.0
214,1.0,0.0,0.0,1.0,0.0,1.0,0.0
90,1.0,0.0,0.0,1.0,0.0,1.0,0.0

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist
0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [37]:
# 5-1. RamdomForest Model 학습, 검증, 평가
# sklearn.ensemble.RamdomForestRegressor
# sklearn.metrics.mean_absolute_error

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error # 평가지표

model_rf = RandomForestRegressor(random_state=1)
model_rf.fit(X_train_pre, y_train)  
pred_val_rf = model_rf.predict(X_val_pre)   # 평가용 예측치

# 평가용 답안과 비교하여 평가지표(MAE) 구하기
MAE_RF = mean_absolute_error(y_val, pred_val_rf)
print("MAE_RF :", MAE_RF)

MAE_RF : 132.73344736842103

In [ ]:
# 5-2. SVR Model 학습, 검증, 평가

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().set_output(transform='pandas')

X_train_sc = scaler.fit_transform(X_train[num_columns])
X_val_sc = scaler.transform(X_val[num_columns])
X_test_sc = scaler.transform(X_test[num_columns])

display(X_train_sc.head(3))
display(X_val_sc.head(3))
display(X_test_sc.head(3))

         temp     atemp  humidity  windspeed
346  1.183168  1.050530 -1.176822  -0.380748
338  0.969955  0.959358 -1.473982   0.085928
238  1.289774  1.322847  0.061346   0.319657
225 -0.948957 -1.131001 -0.582502   0.902807
369  1.396380  1.414019  0.259452   0.552604

         temp     atemp  humidity  windspeed
138 -1.162169 -0.949257 -0.235815  -1.430575
214 -0.629138 -0.676340  1.299513   0.085928
90  -0.842351 -0.949257  0.259452   1.136536
161  0.330318  0.323553  1.646200  -0.147019
102 -0.948957 -1.131001 -0.929188   2.186362

       temp     atemp  humidity  windspeed
0 -1.268776 -1.312745 -0.037708  -0.380748
1 -0.202713 -0.131108 -0.978715   0.786333
2  0.969955  0.959358  0.408032  -1.430575
3  1.502986  1.595763  0.259452   0.085928
4 -0.842351 -0.676340  1.596673  -1.430575

In [ ]:
# SVR모델은 데이터셋을 결함
X_train_pre2 = pd.concat([X_train_en, X_train_sc], axis=1)
X_val_pre2 = pd.concat([X_val_en, X_val_sc], axis=1)
X_test_pre2 = pd.concat([X_test_en, X_test_sc], axis=1)

display(X_train_pre2.head(3))
display(X_val_pre2.head(3))
display(X_test_pre2.head(3))

display(X_train_pre2[num_columns].describe())

# sklearn.svm.SVR
model_svr = SVR()
model_svr.fit(X_train_pre2, y_train)
pred_val_svr = model_svr.predict(X_val_pre2)
MAE_SVR = mean_absolute_error(y_val, pred_val_svr)
print("MAE_SVR :", MAE_SVR)

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist,temp,atemp,humidity,windspeed
346,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.183168,1.050530,-1.176822,-0.380748
338,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.969955,0.959358,-1.473982,0.085928
238,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.289774,1.322847,0.061346,0.319657

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist,temp,atemp,humidity,windspeed
138,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-1.162169,-0.949257,-0.235815,-1.430575
214,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.629138,-0.676340,1.299513,0.085928
90,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.842351,-0.949257,0.259452,1.136536

,holiday_No,holiday_Yes,workingday_No,workingday_Yes,weather_Clear,weather_Light Rain,weather_Mist,temp,atemp,humidity,windspeed
0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,-1.268776,-1.312745,-0.037708,-0.380748
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,-0.202713,-0.131108,-0.978715,0.786333
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.969955,0.959358,0.408032,-1.430575

               temp         atemp      humidity     windspeed
count  2.640000e+02  2.640000e+02  2.640000e+02  2.640000e+02
mean   1.413011e-16  4.037175e-17  1.648513e-16 -7.906134e-17
std    1.001899e+00  1.001899e+00  1.001899e+00  1.001899e+00
min   -2.015019e+00 -2.130295e+00 -3.009310e+00 -1.430575e+00
25%   -8.423508e-01 -8.808776e-01 -7.806083e-01 -6.136956e-01
50%   -9.610713e-02 -4.053530e-02 -8.723453e-02 -3.054561e-02
75%    8.633490e-01  9.593581e-01  8.042461e-01  5.526044e-01
max    2.355836e+00  2.140996e+00  1.943360e+00  4.169541e+00

MAE_SVR : 139.58747471234318

In [38]:
# 6. 모델 비교 및 선택
if MAE_RF < MAE_SVR:
    best_model = model_rf
    pred_test = best_model.predict(X_test_pre)
else:
    best_model = model_svr
    pred_test = best_model.predict(X_test_pre2)

In [ ]:
# 7. 파이프라인(모델, 인코더, 스케일러) 저장, 스케일러 SVR 모델이 선택되면 스케일러도 저장
# joblib.sump() 함수
import joblib
joblib.dump(encoder, 'my_encoder.joblib')
# joblib.dump(scaler, 'my_scaler.joblib')

joblib.dump(best_model, 'my_model.joblib')

In [40]:
# 8. 보고서 -> 결과 파일(csv) 저장
# DataFrame.to_csv() 메서드

result = pd.DataFrame({
    'ID' : test_id,
    '예측치' : pred_test
})

display(result.head())

result.to_csv('result.csv', index=False)

      ID         예측치
0   4775  116.098667
1  10539  254.080000
2   8229   92.070000
3   8677  256.678333
4   5071  103.540000